skip_checks:
  - id: CKV_K8S_23
    suppress_comment: "NetworkPolicy not needed — single-tenant EKS cluster for demo use."

  - id: CKV_K8S_22
    suppress_comment: "Service account token auto-mount acceptable for isolated, low-risk app."

  - id: CKV_AWS_21
    suppress_comment: "CloudTrail in all regions not required for single-region test infra."

  - id: CKV_AWS_158
    suppress_comment: "Wildcard in assume role trust policy is expected for EKS service role."

  - id: CKV_DOCKER_2
    suppress_comment: "HEALTHCHECK not necessary — app monitored via k8s probes."

  - id: CKV_AWS_354
    suppress_comment: "No sensitive data stored — S3 encryption not required."