apiVersion: v1
kind: Pod
metadata:
  name: falco-test
spec:
  containers:
    - name: alpine
      image: alpine
      command: [ "sh", "-c", "sleep 3600" ]  # keep pod running for 1 hour
      securityContext:
        privileged: true
  restartPolicy: Never