apiVersion: v1
kind: Pod
metadata:
  name: falco-test
spec:
  containers:
    - name: alpine
      image: alpine
      command: [ "sh", "-c", "apk add --no-cache bash; bash -c 'echo test > /etc/passwd'" ]
      securityContext:
        privileged: true
  restartPolicy: Never