skip_checks:
  - CKV_AWS_61
  - CKV_AWS_158
  - CKV_AWS_355
  - CKV_AWS_356
  - CKV_AWS_111
  - CKV_K8S_20
  - CKV_K8S_28
  - CKV_K8S_37
  - CKV_K8S_38
  - CKV_K8S_43
  - CKV_K8S_49
  - CKV_DOCKER_2
  - CKV_DOCKER_7