apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5-deployment
  labels:
    app: project5-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project5-app
  template:
    metadata:
      labels:
        app: project5-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: project5-app
          # checkov:skip=CKV_K8S_43: Using :latest tag for automated CI/CD updates
          image: nfroze/project5-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false