name: Secrets Scan with Gitleaks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source=. --report-format=sarif --report-path=gitleaks-results.sarif || true
          if [ ! -f gitleaks-results.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > gitleaks-results.sarif
          fi

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
          category: gitleaks