name: Gitleaks - Hardcoded Secrets Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source=. --no-git --report-format=sarif --report-path=gitleaks-results.sarif || true
          if [ ! -f gitleaks-results.sarif ]; then
            echo '{
              "version": "2.1.0",
              "runs": [
                {
                  "tool": {
                    "driver": {
                      "name": "gitleaks",
                      "informationUri": "https://github.com/gitleaks/gitleaks",
                      "rules": [],
                      "version": "custom"
                    }
                  },
                  "results": []
                }
              ]
            }' > gitleaks-results.sarif
          fi

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks-results.sarif
          category: gitleaks