name: SAST with Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"  # Production-ready security rules
          sarif: semgrep.sarif  # This replaces generateSarif + uploadSarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep